version: '3'

services:
  myapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

##### deployment ###############
  registry:
  # cf.: https://docs.docker.com/registry/deploying/
    image: registry:2.6.2
    ports:
      - "5000:5000"
    volumes:
      - docker_images:/var/lib/registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      # REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      # You can also configure another registry as a pull through cache
      # c.f. https://docs.docker.com/registry/recipes/mirror/
      # REGISTRY_PROXY_REMOTEURL: https://<your-awesome-registry>

  # cf.: https://github.com/kwk/docker-registry-frontend/tree/v2
  ui:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - "8080:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
      # ENV_DOCKER_REGISTRY_USE_SSL: 1
      # ENV_REGISTRY_PROXY_FQDN: ${HOSTNAME}
    links:
      - registry

  data: &data
    image: registry:2.6.2
    volumes:
      - docker_images:/var/lib/registry
      - ./data:/data
    working_dir: /data

  export:
    <<: *data
    command: ash -c "echo 'Exporting docker images to /data/docker_images.bz2...' && tar -C /var/lib/registry -cjf /tmp/docker_images.bz2 ./ && mv /tmp/docker_images.bz2 /data/docker_images.bz2"

  import:
    <<: *data
    command: ash -c "echo 'Importing docker images...' && rm -rf /var/lib/registry/* && tar -C /var/lib/registry -xjf /data/docker_images.bz2"

volumes:
    docker_images:
