version: '3'

volumes:
    docker_images:

services:
  myapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

##### deployment ###############
  registry:
  # cf.: https://docs.docker.com/registry/deploying/
    image: registry:2.6.2
    ports:
      - "5000:5000"
    volumes:
      - docker_images:/var/lib/registry
      #- ./registry/certs:/certs
      #- ./registry/certs:/certs
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      # REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      # configure as pull through cache, cf.:
      # - https://docs.docker.com/registry/recipes/mirror/#configure-the-cache
      # - https://docs.docker.com/registry/configuration/#override-specific-configuration-options
      REGISTRY_PROXY_REMOTEURL: ${REGISTRY_PROXY:-https://registry-1.docker.io}

  # cf.: https://github.com/kwk/docker-registry-frontend/tree/v2
  ui:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - "8080:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
      # ENV_DOCKER_REGISTRY_USE_SSL: 1
      # ENV_REGISTRY_PROXY_FQDN: ${HOSTNAME}
    depends_on:
      - registry

  data: &data
    image: registry:2.6.2
    volumes:
      - docker_images:/var/lib/registry
      - ./data:/data
    working_dir: /data

  export:
    <<: *data
    command: ash -c "echo 'Exporting docker images to /data/docker_images.bz2...' && tar -C /var/lib/registry -cjf /tmp/docker_images.bz2 ./ && mv /tmp/docker_images.bz2 /data/docker_images.bz2"

  import:
    <<: *data
    command: ash -c "echo 'Importing docker images...' && rm -rf /var/lib/registry/* && tar -C /var/lib/registry -xjf /data/docker_images.bz2"
